### ISSUE TITLE
[Error] ParkingRecord 테이블에 데이터 저장 시 id = null 

### ISSUE THREAD

**Issue by seongkyu-lim** [Notherr/ParkingMap#18]
parking record에 값을 저장 후 get요청(?id=1)으로 parking record를 불러올 때 400 에러

-> parking record에 데이터를 저장할 때 id가 null로 저장이 되는 것을 확인.

-> parking record 테이블에 pk 생성 전략 IDENTITY로 자동 생성 어노테이션 추가.

-> 여전히 null로 저장 됨.

**Comment by HyungJunGoo** [comment]
Paking Record 에 redis hash 제거해야했는데 제거 하고 혹시 다시 해볼수 있는지..? 내일 이른 오후부터 나도 해볼 수 있을듯

**Comment by seongkyu-lim** [comment]
> Paking Record 에 redis hash 제거해야했는데 제거 하고 혹시 다시 해볼수 있는지..? 내일 이른 오후부터 나도 해볼 수 있을듯

redish hash 제거 하니 잘되네요! 👍🏻 같이 제거했던거 같은데 왜 안되있었지 ㅋㅋ

record cache는 여전히 null로 저장되는 것으로 보입니다. redish 적용이 완전히 되지 않아 그런걸까요 ?

**Comment by HyungJunGoo** [comment]
record cache가 null로 저장되는 것이 아니라 애초에 redis 에 저장되고 jpa설정과 h2 db에 저장하는 과정이 생략된 것으로 보임. 
-> embedded redis 에는 정상적으로 저장되어 있을 것
cache에서  db에 저장이 되는 것을 추가해야하는 것으로 보임
